# Site settings
title: Dillon Matchett
description: bombasticSlacks Online
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://dillonmatchett.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dillon Matchett
user_description: A software developer currently working for the Canadian federal government. Experience in small startups and larger teams as a scrum master, CI/CD expert, and full-stack developer. Further dedicating leisure time to open source and publicly available personal projects. Full resume available on request.
user_title: Developer
email: dillon.matchett@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: dillon-matchett
github_username: bombasticSlacks
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ["package.json", "src", "node_modules", "vendor"]
